-- MySQL Script generated by MySQL Workbench
-- Sun Dec 18 22:14:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema heroku_abbadfb93a6a1d4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_abbadfb93a6a1d4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_abbadfb93a6a1d4` DEFAULT CHARACTER SET utf8 ;
USE `heroku_abbadfb93a6a1d4` ;

-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Mercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Mercado` (
  `idMercado` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMercado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Mercado_idMercado` INT NOT NULL,
  PRIMARY KEY (`idDepartamento`, `Mercado_idMercado`),
  INDEX `fk_Departamento_Mercado1_idx` (`Mercado_idMercado` ASC),
  CONSTRAINT `fk_Departamento_Mercado1`
    FOREIGN KEY (`Mercado_idMercado`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Mercado` (`idMercado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Fornecedor` (
  `idFornecedor` INT NOT NULL AUTO_INCREMENT,
  `Filial` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(20) NOT NULL,
  `Tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Produtos` (
  `idProdutos` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Preço` FLOAT NOT NULL,
  `QuantidadeProduto` varchar(10) NOT NULL,
  PRIMARY KEY (`idProdutos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Funcionario` (
  `CPF Funcionario` VARCHAR(30) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `Funçao` VARCHAR(45) NOT NULL,
  `DataDeAdmissao` DATE NOT NULL,
  `Departamento_idDepartamento` INT NOT NULL,
  PRIMARY KEY (`CPF Funcionario`, `Departamento_idDepartamento`),
  INDEX `fk_Funcionario_Departamento_idx` (`Departamento_idDepartamento` ASC),
  CONSTRAINT `fk_Funcionario_Departamento`
    FOREIGN KEY (`Departamento_idDepartamento`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Cliente` (
  `CPFcliente` VARCHAR(30) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Mercado_idMercado` INT NOT NULL,
  PRIMARY KEY (`CPFcliente`, `Mercado_idMercado`),
  INDEX `fk_Cliente_Mercado1_idx` (`Mercado_idMercado` ASC),
  CONSTRAINT `fk_Cliente_Mercado1`
    FOREIGN KEY (`Mercado_idMercado`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Mercado` (`idMercado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Compra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `Cliente_CPFcliente` VARCHAR(30) NOT NULL,
  `Cliente_Mercado_idMercado` INT NOT NULL,
  `DataCompra` DATE NOT NULL,
  PRIMARY KEY (`idCompra`, `Cliente_CPFcliente`, `Cliente_Mercado_idMercado`),
  INDEX `fk_Compra_Cliente1_idx` (`Cliente_CPFcliente` ASC, `Cliente_Mercado_idMercado` ASC),
  CONSTRAINT `fk_Compra_Cliente1`
    FOREIGN KEY (`Cliente_CPFcliente` , `Cliente_Mercado_idMercado`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Cliente` (`CPFcliente` , `Mercado_idMercado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Produtos_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Produtos_Compra` (
  `Compra_idCompra` INT NOT NULL,
  `Compra_Cliente_CPFcliente` VARCHAR(30) NOT NULL,
  `Compra_Cliente_Mercado_idMercado` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`Compra_idCompra`, `Compra_Cliente_CPFcliente`, `Compra_Cliente_Mercado_idMercado`, `Produtos_idProdutos`),
  INDEX `fk_Produtos_has_Compra_Compra1_idx` (`Compra_idCompra` ASC, `Compra_Cliente_CPFcliente` ASC, `Compra_Cliente_Mercado_idMercado` ASC),
  INDEX `fk_Produtos_has_Compra_Produtos1_idx` (`Produtos_idProdutos` ASC),
  CONSTRAINT `fk_Produtos_has_Compra_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produtos_has_Compra_Compra1`
    FOREIGN KEY (`Compra_idCompra` , `Compra_Cliente_CPFcliente` , `Compra_Cliente_Mercado_idMercado`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Compra` (`idCompra` , `Cliente_CPFcliente` , `Cliente_Mercado_idMercado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heroku_abbadfb93a6a1d4`.`Fornecedor_Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_abbadfb93a6a1d4`.`Fornecedor_Produtos` (
  `Fornecedor_idFornecedor` INT NOT NULL,
  `Produtos_idProdutos` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_idFornecedor`, `Produtos_idProdutos`),
  INDEX `fk_Fornecedor_has_Produtos_Produtos1_idx` (`Produtos_idProdutos` ASC),
  INDEX `fk_Fornecedor_has_Produtos_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Produtos_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Produtos_Produtos1`
    FOREIGN KEY (`Produtos_idProdutos`)
    REFERENCES `heroku_abbadfb93a6a1d4`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
